name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t chat-app .

    - name: Push Docker image
      run: |
        docker tag chat-app:latest ${{ secrets.DOCKER_USERNAME }}/chat-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/chat-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/chat-app:latest
          docker stop chat || true && docker rm chat || true
          docker run -d --name chat -p 80:80 ${{ secrets.DOCKER_USERNAME }}/chat-app:latest

